comment: false

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project: yes
    patch: yes
    changes: no

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null