name: Upload Python Package to PyPI

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.1.0; prevent CWE-829
      with:
        enable-cache: true
        python-version: 3.14
    - name: Build wheel
      run: uv build --wheel
    - name: Upload wheel artifact
      uses: actions/upload-artifact@v7
      with:
        name: dist
        path: dist/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: dist
        path: dist
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        packages-dir: dist

