[server]
showEmailPrompt = false

[theme]
base = "dark"
primaryColor = "#C41E3A" # Cardinal Red
backgroundColor = "#146B3A" # Forest Green
secondaryBackgroundColor = "#2F845A" # Lighter green

[client]
toolbarMode = "viewer"